build:
  nodes:
    analysis:
      tests:
        override:
          - phpcs-run
          - php-scrutinizer-run
    my-tests:
      environment:
        php:
          version: 7.3
      tests:
        override:
          - command: composer app:test
            coverage:
              file: var/phpunit/coverage.xml
              format: php-clover
